import os
import sys
import torch
import numpy as np

# Include parent folder in path
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from llm_probe.config import MODEL_NAME, DEVICE
from llm_probe.models.loader import load_model, load_tokenizer
from demo.inference import load_probe_payload, generate_with_probe

def main():
    print("Loading trained probe...")
    payload = load_probe_payload("results/memorization/probe.joblib")
    probe = payload['probe']
    scaler = payload['scaler']
    selected_layers = payload['selected_layers']
    representation_type = payload['representation_type']
    
    print("Loading LLM model and tokenizer...")
    model = load_model(MODEL_NAME, DEVICE)
    tokenizer = load_tokenizer(MODEL_NAME)
    
    prompts = {
        "High Memorization (Alice)": "Alice was beginning to get very tired of sitting by her sister on the bank,",
        "High Memorization (Moby Dick)": "Call me Ishmael. Some years ago—never mind how long precisely—",
        "Low Memorization (Invented)": "The spaceship descended slowly into the neon-lit valleys of Sector 7G, where robots danced to jazz.",
        "Out-of-Distribution (General Knowledge)": "What is the capital of France and what are its major landmarks?"
    }
    
    output_lines = [
        "# LLM Probe - Live Inference Demo Test Results",
        "",
        "This file contains the scored output tokens and risk scores for the 4 test prompts generated by the live memorization probe.",
        ""
    ]
    
    for name, prompt in prompts.items():
        print(f"\nEvaluating prompt '{name}'...")
        results = generate_with_probe(
            prompt=prompt,
            model=model,
            tokenizer=tokenizer,
            probe=probe,
            scaler=scaler,
            selected_layers=selected_layers,
            representation_type=representation_type,
            max_tokens=40
        )
        
        # Build text string with scores
        inline_tokens = []
        scores = []
        for item in results:
            token = item['token']
            score = item['mem_score']
            scores.append(score)
            inline_tokens.append(f"{token}[MEM:{score:.2f}]")
            
        max_score = max(scores) if scores else 0.0
        avg_score = sum(scores) / len(scores) if scores else 0.0
        risk_level = "HIGH" if max_score >= 0.6 else ("MEDIUM" if max_score >= 0.3 else "LOW")
        
        line = f"## {name}\n"
        line += f"**Prompt**: `{prompt}`\n\n"
        line += f"**Generated Output**:\n"
        line += f"\"{''.join(inline_tokens)}\"\n\n"
        line += f"**Inference Statistics**:\n"
        line += f"- Overall Risk Level: **{risk_level}**\n"
        line += f"- Max Token Score: `{max_score:.4f}`\n"
        line += f"- Average Token Score: `{avg_score:.4f}`\n\n"
        line += "---\n\n"
        
        output_lines.append(line)
        print(f"Finished '{name}': Risk={risk_level}, Max Score={max_score:.4f}")
        
    # Save file
    output_path = "results/memorization/demo_test_results.md"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(output_lines))
    print(f"\nAll tests completed successfully. Saved report to: {output_path}")

if __name__ == "__main__":
    main()
